# Generated by Django 5.0.6 on 2026-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите короткое название судебного дела', max_length=255, verbose_name='Название дела')),
                ('text', models.TextField(help_text='Введите полный текст судебного дела', verbose_name='Текст дела')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(help_text='Укажите тип документа (например: иск, ходатайство, заключение)', max_length=100, verbose_name='Тип документа')),
                ('text', models.TextField(help_text='Сюда будет помещён сгенерированный текст документа', verbose_name='Текст документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
