# Generated by Django 5.0.6 on 2025-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='text',
            field=models.TextField(help_text='Введите полный текст судебного дела', verbose_name='Текст дела'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(help_text='Введите короткое название судебного дела', max_length=255, verbose_name='Название дела'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(help_text='Укажите тип документа (например: иск, ходатайство, заключение)', max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='text',
            field=models.TextField(help_text='Сюда будет помещён сгенерированный текст документа', verbose_name='Текст документа'),
        ),
    ]
